proxy-providers:
  aca:
    type: file
    path: ./proxy_provider/aca.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  niceduck:
    type: file
    path: ./proxy_provider/niceduck.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  赔钱机场:
    type: file
    path: ./proxy_provider/赔钱机场.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
